version: "3.9"

services:
  ml-eaves-droid:
    build: .
    image: ${IMAGE_ML_EAVES_DROID:-ml-eaves-droid}:latest
    container_name: ${CONTAINER_ML_EAVES_DROID:-ml-eaves-droid}
    ports:
      - "${ML_EAVES_DROID_API_PORT:-9071}:9070"
      - "${ML_EAVES_DROID_TF_SERVING_PORT:-9072}:9072"
      - "${ML_EAVES_DROID_METRICS_PORT:-9073}:9073"
      - "${ML_EAVES_DROID_DEBUG_PORT:-9094}:9094"
      - "${ML_EAVES_DROID_MGMT_PORT:-9095}:9095"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - hosts-shared-network

networks:
  hosts-shared-network:
    name: hosts-shared-network
    external: true
