-- =============================================================================
-- Migration: ML Jobs & Results Tables
-- =============================================================================
-- Run against db_eaves_droid:
--   mysql -h 127.0.0.1 -P 9306 -u root -p db_eaves_droid < migrations/001_ml_jobs_tables.sql
-- =============================================================================

-- ── ml_jobs ─────────────────────────────────────────────────────────────────
-- Tracks each anomaly detection run submitted by the PHP side.
-- The Python FastAPI backend picks up 'pending' jobs, updates status as it
-- progresses, and stores findings in ml_results.
CREATE TABLE IF NOT EXISTS ml_jobs (
    id                  INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id             INT UNSIGNED NOT NULL,
    engine              VARCHAR(20)  NOT NULL DEFAULT 'python',
    algorithms          JSON         NOT NULL COMMENT '["sms_bert","calls_isolation",...]',

    -- Job scope: 'full' = analyze everything, 'incremental' = only new entries
    scope               ENUM('full','incremental') NOT NULL DEFAULT 'full',

    -- For incremental runs: the cutoff timestamp; Python queries
    -- WHERE created_at > incremental_since for each table
    incremental_since   DATETIME     NULL COMMENT 'Cutoff for incremental analysis',

    status              ENUM('pending','running','completed','failed')
                        NOT NULL DEFAULT 'pending',
    results_count       INT UNSIGNED NOT NULL DEFAULT 0,
    error_msg           TEXT         NULL,
    timing_ms           INT UNSIGNED NOT NULL DEFAULT 0,

    created_at          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at          DATETIME     NULL,
    completed_at        DATETIME     NULL,

    INDEX idx_user_status (user_id, status),
    INDEX idx_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── ml_results ──────────────────────────────────────────────────────────────
-- One row per anomaly finding generated by a job.
-- The PHP side reads this table after the job completes to render the wizard.
CREATE TABLE IF NOT EXISTS ml_results (
    id              INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    job_id          INT UNSIGNED NOT NULL,
    user_id         INT UNSIGNED NOT NULL,

    category        VARCHAR(50)  NOT NULL COMMENT 'sms | contacts | call_logs | locations | apps | files | activity | device_info',
    algorithm       VARCHAR(100) NOT NULL COMMENT 'Display name: Activity Sequence Predictor (MLP)',
    algorithm_id    VARCHAR(50)  NOT NULL COMMENT 'Machine name: act_lstm',
    severity        ENUM('High','Medium','Low') NOT NULL,
    anomaly         TEXT         NOT NULL COMMENT 'Human-readable description of the finding',

    score           DECIMAL(10,4) NOT NULL DEFAULT 0.0000,
    event_timestamp DATETIME     NULL     COMMENT 'When the anomalous event occurred (from source data)',
    details         JSON         NULL     COMMENT 'Arbitrary metadata: feature vectors, z-scores, etc.',

    created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_job        (job_id),
    INDEX idx_user       (user_id),
    INDEX idx_job_severity (job_id, severity),

    CONSTRAINT fk_ml_results_job
        FOREIGN KEY (job_id) REFERENCES ml_jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ── ml_analysis_tracking ────────────────────────────────────────────────────
-- Tracks per-user per-category analysis progress so the PHP UI can show
-- "X new entries since last analysis" and support incremental jobs.
CREATE TABLE IF NOT EXISTS ml_analysis_tracking (
    user_id         INT UNSIGNED    NOT NULL,
    category        VARCHAR(50)     NOT NULL COMMENT 'sms | contacts | call_logs | locations | apps | files | activity | device_info',

    -- For tables with an auto-increment PK, the last ID that was analyzed
    last_id         BIGINT UNSIGNED NOT NULL DEFAULT 0,

    -- For timestamp-based tables, the cutoff used for incremental analysis
    last_analyzed_at DATETIME       NULL,

    -- Total rows counted at the time of the last FULL analysis
    total_analyzed  INT UNSIGNED    NOT NULL DEFAULT 0,

    updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (user_id, category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
