<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CreateTblFeatureTiers extends Migration
{
    public function up()
    {
        $this->forge->addField([
            'id' => [
                'type'           => 'INT',
                'constraint'     => 11,
                'unsigned'       => true,
                'auto_increment' => true,
            ],
            'category_type' => [
                'type'       => 'ENUM',
                'constraint' => ['hardware', 'software'],
                'null'       => false,
            ],
            'slug' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
                'unique'     => true,
            ],
            'label' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
            ],
            'description' => [
                'type' => 'TEXT',
                'null' => true,
            ],
            'icon' => [
                'type'       => 'VARCHAR',
                'constraint' => 100,
                'null'       => false,
            ],
            'color_class' => [
                'type'       => 'VARCHAR',
                'constraint' => 50,
                'null'       => false,
            ],
            'bg_class' => [
                'type'       => 'VARCHAR',
                'constraint' => 50,
                'null'       => false,
            ],
            'required_tier' => [
                'type'       => 'ENUM',
                'constraint' => ['free', 'gold', 'platinum'],
                'default'    => 'free',
            ],
            'created_at datetime default current_timestamp',
            'updated_at datetime default current_timestamp on update current_timestamp',
        ]);

        $this->forge->addKey('id', true);
        $this->forge->createTable('tbl_feature_tiers');

        // Populate initial feature distribution matrix
        $features = [
            // 🟢 Free Tier
            [
                'category_type' => 'software',
                'slug'          => 'default_apps',
                'label'         => 'Default Apps',
                'description'   => 'Default browser, dialer, SMS, launcher handlers',
                'icon'          => 'fas fa-cogs',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'alarms',
                'label'         => 'Alarms & Jobs',
                'description'   => 'Scheduled JobScheduler jobs and AlarmManager alarms',
                'icon'          => 'fas fa-clock',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'free',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'system_locale',
                'label'         => 'System Locale',
                'description'   => 'Locale, region, timezone, system fonts',
                'icon'          => 'fas fa-language',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'free',
            ],

            // 🟡 Gold Tier
            [
                'category_type' => 'hardware',
                'slug'          => 'bluetooth',
                'label'         => 'Bluetooth',
                'description'   => 'Adapter, paired devices, enabled state',
                'icon'          => 'fas fa-bluetooth-b',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-primary',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'cell_towers',
                'label'         => 'Cell Towers',
                'description'   => 'GSM/LTE/NR, signal strength, operator',
                'icon'          => 'fas fa-broadcast-tower',
                'color_class'   => 'card-orange',
                'bg_class'      => 'bg-orange',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'battery_stats',
                'label'         => 'Battery',
                'description'   => 'Level, charging, health, temperature',
                'icon'          => 'fas fa-battery-three-quarters',
                'color_class'   => 'card-success',
                'bg_class'      => 'bg-success',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'display_info',
                'label'         => 'Display',
                'description'   => 'Resolution, DPI, refresh rate, rotation',
                'icon'          => 'fas fa-tv',
                'color_class'   => 'card-pink',
                'bg_class'      => 'bg-pink',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'storage',
                'label'         => 'Storage',
                'description'   => 'Volumes, capacity, available space',
                'icon'          => 'fas fa-hdd',
                'color_class'   => 'card-teal',
                'bg_class'      => 'bg-teal',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'processes',
                'label'         => 'Running Processes',
                'description'   => 'Process snapshots',
                'icon'          => 'fas fa-tasks',
                'color_class'   => 'card-dark',
                'bg_class'      => 'bg-dark',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'accessibility',
                'label'         => 'Accessibility',
                'description'   => 'Enabled accessibility services and settings',
                'icon'          => 'fas fa-universal-access',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'input_methods',
                'label'         => 'Input Methods',
                'description'   => 'Active keyboards and input method engines',
                'icon'          => 'fas fa-keyboard',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'saved_wifi',
                'label'         => 'Saved WiFi',
                'description'   => 'Configured WiFi networks and security types',
                'icon'          => 'fas fa-wifi',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'gold',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'data_usage',
                'label'         => 'Data Usage',
                'description'   => 'Per-app mobile and WiFi data usage',
                'icon'          => 'fas fa-chart-line',
                'color_class'   => 'card-success',
                'bg_class'      => 'bg-success',
                'required_tier' => 'gold',
            ],

            // 🔴 Platinum Tier (Hardware)
            [
                'category_type' => 'hardware',
                'slug'          => 'hardware_network',
                'label'         => 'Network Interfaces',
                'description'   => 'Interfaces, routes, ARP, WiFi Passpoint',
                'icon'          => 'fas fa-network-wired',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'nfc',
                'label'         => 'NFC',
                'description'   => 'Available, enabled, secure element',
                'icon'          => 'fas fa-credit-card',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'power_rails',
                'label'         => 'Power Rails',
                'description'   => 'Voltage, current, power per rail',
                'icon'          => 'fas fa-bolt',
                'color_class'   => 'card-orange',
                'bg_class'      => 'bg-orange',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'thermal',
                'label'         => 'Thermal',
                'description'   => 'Temperature zones, throttling, governors',
                'icon'          => 'fas fa-thermometer-half',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'sensors',
                'label'         => 'Sensors',
                'description'   => 'Accelerometer, gyro, magnetometer, etc.',
                'icon'          => 'fas fa-ruler',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'hardware_graphics',
                'label'         => 'Graphics (GPU)',
                'description'   => 'GPU renderer, media codecs, input devices',
                'icon'          => 'fas fa-desktop',
                'color_class'   => 'card-purple',
                'bg_class'      => 'bg-purple',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'audio_devices',
                'label'         => 'Audio Devices',
                'description'   => 'Sinks, sources, sample rates, latency',
                'icon'          => 'fas fa-volume-up',
                'color_class'   => 'card-purple',
                'bg_class'      => 'bg-purple',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'camera_info',
                'label'         => 'Camera',
                'description'   => 'Capabilities, focal lengths, HDR, video modes',
                'icon'          => 'fas fa-camera',
                'color_class'   => 'card-pink',
                'bg_class'      => 'bg-pink',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'usb_devices',
                'label'         => 'USB Devices',
                'description'   => 'Connected peripherals, power, speed',
                'icon'          => 'fas fa-usb',
                'color_class'   => 'card-teal',
                'bg_class'      => 'bg-teal',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'gnss_hardware',
                'label'         => 'GNSS / GPS',
                'description'   => 'Constellations, antenna, AGPS, raw measurements',
                'icon'          => 'fas fa-satellite',
                'color_class'   => 'card-warning',
                'bg_class'      => 'bg-warning',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'biometric',
                'label'         => 'Biometric',
                'description'   => 'Fingerprint, face, iris sensors',
                'icon'          => 'fas fa-fingerprint',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'vibration',
                'label'         => 'Vibration',
                'description'   => 'Actuator type, amplitude, frequency',
                'icon'          => 'fas fa-wave-square',
                'color_class'   => 'card-dark',
                'bg_class'      => 'bg-dark',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'device',
                'label'         => 'Device Context',
                'description'   => 'Battery level, clipboard snapshot, locale, timezone',
                'icon'          => 'fas fa-mobile-alt',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-primary',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'sim-configs',
                'label'         => 'SIM Configs',
                'description'   => 'SIM card configuration, ICCID, carrier, slot info',
                'icon'          => 'fas fa-sim-card',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'hardware',
                'slug'          => 'proc_info',
                'label'         => 'Proc Info',
                'description'   => 'Kernel /proc dump, memory, cpuinfo, mounts',
                'icon'          => 'fas fa-terminal',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'platinum',
            ],

            // 🔴 Platinum Tier (Software)
            [
                'category_type' => 'software',
                'slug'          => 'accounts',
                'label'         => 'Accounts',
                'description'   => 'User accounts, email addresses, and credentials',
                'icon'          => 'fas fa-user-circle',
                'color_class'   => 'card-primary',
                'bg_class'      => 'bg-primary',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'email',
                'label'         => 'Email Accounts',
                'description'   => 'Configured email accounts and providers',
                'icon'          => 'fas fa-envelope',
                'color_class'   => 'card-primary',
                'bg_class'      => 'bg-primary',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'calendar',
                'label'         => 'Calendar',
                'description'   => 'Calendar events, reminders, and schedule data',
                'icon'          => 'fas fa-calendar-alt',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'app-usage',
                'label'         => 'App Usage',
                'description'   => 'Application usage time and frequency statistics',
                'icon'          => 'fas fa-chart-pie',
                'color_class'   => 'card-success',
                'bg_class'      => 'bg-success',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'notifications',
                'label'         => 'Notifications',
                'description'   => 'Notifications from apps with titles',
                'icon'          => 'fas fa-bell',
                'color_class'   => 'card-purple',
                'bg_class'      => 'bg-purple',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'security_audit',
                'label'         => 'Security Audit',
                'description'   => 'Security findings, permissions, and vulnerability data',
                'icon'          => 'fas fa-shield-alt',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'app_security',
                'label'         => 'App Security',
                'description'   => 'Device admins, permission maps, running services',
                'icon'          => 'fas fa-user-shield',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'network_security',
                'label'         => 'Network Security',
                'description'   => 'DNS config, VPN status, proxy settings',
                'icon'          => 'fas fa-lock',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'app_permissions',
                'label'         => 'App Permissions',
                'description'   => 'Requested/granted runtime permissions per app',
                'icon'          => 'fas fa-user-shield',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'browser_history',
                'label'         => 'Browser History',
                'description'   => 'Browsing history, bookmarks, and searches',
                'icon'          => 'fas fa-globe',
                'color_class'   => 'card-orange',
                'bg_class'      => 'bg-orange',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'clipboard',
                'label'         => 'Clipboard',
                'description'   => 'Copied text, URIs, and source applications',
                'icon'          => 'fas fa-paste',
                'color_class'   => 'card-pink',
                'bg_class'      => 'bg-pink',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'content_providers',
                'label'         => 'Content Providers',
                'description'   => 'Provider authorities, permissions, exported flags',
                'icon'          => 'fas fa-database',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'crash_logs',
                'label'         => 'Crash Logs',
                'description'   => 'Crashes, exceptions, and stack traces',
                'icon'          => 'fas fa-bug',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'digital_wellbeing',
                'label'         => 'Digital Wellbeing',
                'description'   => 'Screen time, focus/bedtime modes, app timers',
                'icon'          => 'fas fa-smile',
                'color_class'   => 'card-success',
                'bg_class'      => 'bg-success',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'doze_standby',
                'label'         => 'Doze & Standby',
                'description'   => 'Doze state, battery saver, standby buckets',
                'icon'          => 'fas fa-battery-half',
                'color_class'   => 'card-info',
                'bg_class'      => 'bg-info',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'health_data',
                'label'         => 'Health Data',
                'description'   => 'Steps, heart rate, sleep, and workouts',
                'icon'          => 'fas fa-heartbeat',
                'color_class'   => 'card-success',
                'bg_class'      => 'bg-success',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'keyboard_input',
                'label'         => 'Keyboard Input',
                'description'   => 'Keystroke logs and type indicators',
                'icon'          => 'fas fa-keyboard',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'keyguard',
                'label'         => 'Keyguard Events',
                'description'   => 'Unlock/lock events and auth methods',
                'icon'          => 'fas fa-lock',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'screenshots',
                'label'         => 'Screenshots',
                'description'   => 'Background screenshots timeline',
                'icon'          => 'fas fa-camera',
                'color_class'   => 'card-pink',
                'bg_class'      => 'bg-pink',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'screen_state',
                'label'         => 'Screen State',
                'description'   => 'Screen on/off events and unlock attempts',
                'icon'          => 'fas fa-desktop',
                'color_class'   => 'card-success',
                'bg_class'      => 'bg-success',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'vpn_config',
                'label'         => 'VPN Config',
                'description'   => 'Corporate VPN configuration details',
                'icon'          => 'fas fa-shield-alt',
                'color_class'   => 'card-danger',
                'bg_class'      => 'bg-danger',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'running_processes',
                'label'         => 'Running Processes',
                'description'   => 'Detailed process list with memory and CPU',
                'icon'          => 'fas fa-cogs',
                'color_class'   => 'card-success',
                'bg_class'      => 'bg-success',
                'required_tier' => 'platinum',
            ],
            [
                'category_type' => 'software',
                'slug'          => 'telephony_network',
                'label'         => 'Mobile Network',
                'description'   => 'IMS/VoLTE, data roaming, carrier config',
                'icon'          => 'fas fa-signal',
                'color_class'   => 'card-secondary',
                'bg_class'      => 'bg-secondary',
                'required_tier' => 'platinum',
            ],
        ];

        $this->db->table('tbl_feature_tiers')->insertBatch($features);
    }

    public function down()
    {
        $this->forge->dropTable('tbl_feature_tiers');
    }
}
