<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CreateTblDevices extends Migration
{
    public function up()
    {
        $this->db->query('CREATE TABLE `tbl_devices` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `device_model` varchar(255) DEFAULT NULL,
  `device_brand` varchar(100) DEFAULT NULL,
  `device_manufacturer` varchar(100) DEFAULT NULL,
  `device_product` varchar(100) DEFAULT NULL,
  `device_device` varchar(100) DEFAULT NULL,
  `device_board` varchar(100) DEFAULT NULL,
  `device_hardware` varchar(100) DEFAULT NULL,
  `android_version` varchar(50) DEFAULT NULL,
  `android_sdk_int` int DEFAULT NULL,
  `android_codename` varchar(50) DEFAULT NULL,
  `android_incremental` varchar(50) DEFAULT NULL,
  `android_base_os` varchar(100) DEFAULT NULL,
  `android_security_patch` varchar(50) DEFAULT NULL,
  `build_id` varchar(100) DEFAULT NULL,
  `build_type` varchar(50) DEFAULT NULL,
  `build_tags` varchar(255) DEFAULT NULL,
  `build_fingerprint` text,
  `build_time` bigint DEFAULT NULL,
  `build_user` varchar(100) DEFAULT NULL,
  `build_host` varchar(100) DEFAULT NULL,
  `build_display` varchar(255) DEFAULT NULL,
  `android_id` varchar(100) DEFAULT NULL,
  `display_width` int DEFAULT NULL,
  `display_height` int DEFAULT NULL,
  `display_density` float DEFAULT NULL,
  `display_density_dpi` int DEFAULT NULL,
  `display_scaled_density` float DEFAULT NULL,
  `display_xdpi` float DEFAULT NULL,
  `display_ydpi` float DEFAULT NULL,
  `cpu_cores` int DEFAULT NULL,
  `cpu_abi` varchar(50) DEFAULT NULL,
  `cpu_abis` varchar(255) DEFAULT NULL,
  `memory_total_mb` int DEFAULT NULL,
  `memory_free_mb` int DEFAULT NULL,
  `internal_storage_total_gb` int DEFAULT NULL,
  `internal_storage_free_gb` int DEFAULT NULL,
  `internal_storage_usable_gb` int DEFAULT NULL,
  `external_storage_total_gb` int DEFAULT NULL,
  `external_storage_free_gb` int DEFAULT NULL,
  `phone_number` varchar(50) DEFAULT NULL,
  `sim_operator` varchar(100) DEFAULT NULL,
  `network_operator` varchar(100) DEFAULT NULL,
  `sim_country` varchar(10) DEFAULT NULL,
  `network_country` varchar(10) DEFAULT NULL,
  `imei` varchar(50) DEFAULT NULL,
  `meid` varchar(50) DEFAULT NULL,
  `device_id` varchar(50) DEFAULT NULL,
  `sim_state` varchar(50) DEFAULT NULL,
  `language` varchar(10) DEFAULT NULL,
  `country` varchar(10) DEFAULT NULL,
  `timezone` varchar(100) DEFAULT NULL,
  `timezone_offset` int DEFAULT NULL,
  `current_time` bigint DEFAULT NULL,
  `current_time_formatted` varchar(100) DEFAULT NULL,
  `battery_charging` tinyint(1) DEFAULT \'0\',
  `battery_level` float DEFAULT NULL,
  `sensor_count` int DEFAULT NULL,
  `mac_address` varchar(50) DEFAULT NULL,
  `kernel_info` text,
  `is_emulator` tinyint(1) DEFAULT \'0\',
  `is_rooted` tinyint(1) DEFAULT \'0\',
  `app_package` varchar(255) DEFAULT NULL,
  `app_version` varchar(50) DEFAULT NULL,
  `app_version_code` int DEFAULT NULL,
  `app_first_install` bigint DEFAULT NULL,
  `app_last_update` bigint DEFAULT NULL,
  `extraction_timestamp` bigint NOT NULL,
  `extractor_version` varchar(20) DEFAULT \'1.0\',
  `raw_device_json` longtext,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT \'1\',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_device_fingerprint` (`android_id`,`device_model`,`android_version`),
  KEY `android_id` (`android_id`),
  KEY `device_model` (`device_model`),
  KEY `android_version` (`android_version`),
  KEY `extraction_timestamp` (`extraction_timestamp`),
  KEY `created_at` (`created_at`),
  KEY `is_active` (`is_active`),
  KEY `device_brand` (`device_brand`),
  KEY `android_sdk_int` (`android_sdk_int`),
  KEY `phone_number` (`phone_number`),
  KEY `sim_operator` (`sim_operator`),
  KEY `imei` (`imei`),
  KEY `is_rooted` (`is_rooted`),
  KEY `app_package` (`app_package`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3');
    }

    public function down()
    {
        $this->db->query('DROP TABLE IF EXISTS `tbl_devices`');
    }
}
