<?php

namespace App\Database\Migrations;

use CodeIgniter\Database\Migration;

class CreateTblDeviceProfile extends Migration
{
    public function up()
    {
        $this->db->query('CREATE TABLE `tbl_device_profile` (
  `counter` int unsigned NOT NULL AUTO_INCREMENT,
  `device_model` varchar(255) DEFAULT NULL,
  `device_brand` varchar(255) DEFAULT NULL,
  `device_manufacturer` varchar(255) DEFAULT NULL,
  `device_product` varchar(255) DEFAULT NULL,
  `device_device` varchar(255) DEFAULT NULL,
  `device_board` varchar(255) DEFAULT NULL,
  `device_hardware` varchar(255) DEFAULT NULL,
  `android_version` varchar(50) DEFAULT NULL,
  `android_sdk_int` int DEFAULT NULL,
  `android_codename` varchar(50) DEFAULT NULL,
  `android_incremental` varchar(255) DEFAULT NULL,
  `android_base_os` varchar(255) DEFAULT NULL,
  `android_security_patch` varchar(50) DEFAULT NULL,
  `build_id` varchar(255) DEFAULT NULL,
  `build_type` varchar(50) DEFAULT NULL,
  `build_tags` varchar(255) DEFAULT NULL,
  `build_fingerprint` text,
  `build_time` bigint DEFAULT NULL,
  `build_user` varchar(255) DEFAULT NULL,
  `build_host` varchar(255) DEFAULT NULL,
  `build_display` text,
  `android_id` varchar(255) DEFAULT NULL,
  `display_width` int DEFAULT NULL,
  `display_height` int DEFAULT NULL,
  `display_density` float DEFAULT NULL,
  `display_density_dpi` int DEFAULT NULL,
  `display_scaled_density` float DEFAULT NULL,
  `display_xdpi` float DEFAULT NULL,
  `display_ydpi` float DEFAULT NULL,
  `cpu_cores` int DEFAULT NULL,
  `cpu_abi` varchar(255) DEFAULT NULL,
  `cpu_abis` text,
  `memory_total_mb` bigint DEFAULT NULL,
  `memory_free_mb` bigint DEFAULT NULL,
  `internal_storage_total_gb` bigint DEFAULT NULL,
  `internal_storage_free_gb` bigint DEFAULT NULL,
  `internal_storage_usable_gb` bigint DEFAULT NULL,
  `external_storage_total_gb` bigint DEFAULT NULL,
  `external_storage_free_gb` bigint DEFAULT NULL,
  `phone_number` varchar(50) DEFAULT NULL,
  `sim_operator` varchar(255) DEFAULT NULL,
  `network_operator` varchar(255) DEFAULT NULL,
  `sim_country` varchar(50) DEFAULT NULL,
  `network_country` varchar(50) DEFAULT NULL,
  `imei` varchar(255) DEFAULT NULL,
  `meid` varchar(255) DEFAULT NULL,
  `device_checksum` varchar(100) DEFAULT NULL,
  `fcm_token` text,
  `device_id` varchar(255) DEFAULT NULL,
  `owner_id` int unsigned DEFAULT NULL,
  `sim_state` varchar(50) DEFAULT NULL,
  `language` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `timezone` varchar(255) DEFAULT NULL,
  `timezone_offset` int DEFAULT NULL,
  `current_time` bigint DEFAULT NULL,
  `current_time_formatted` varchar(255) DEFAULT NULL,
  `battery_charging` tinyint(1) DEFAULT NULL,
  `battery_level` float DEFAULT NULL,
  `sensor_count` int DEFAULT NULL,
  `mac_address` varchar(50) DEFAULT NULL,
  `kernel_info` text,
  `is_emulator` tinyint(1) DEFAULT NULL,
  `is_rooted` tinyint(1) DEFAULT NULL,
  `app_package` varchar(255) DEFAULT NULL,
  `app_version` varchar(50) DEFAULT NULL,
  `app_version_code` bigint DEFAULT NULL,
  `app_first_install` bigint DEFAULT NULL,
  `app_last_update` bigint DEFAULT NULL,
  `extraction_timestamp` bigint DEFAULT NULL,
  `extractor_version` varchar(50) DEFAULT NULL,
  `device_ip_address` varchar(45) DEFAULT NULL,
  `screen_size_inches` float DEFAULT NULL,
  `display_refresh_rate` float DEFAULT NULL,
  `display_mode_width` int DEFAULT NULL,
  `display_mode_height` int DEFAULT NULL,
  `display_mode_refresh` float DEFAULT NULL,
  `cpu_detail` text,
  `memory_available_mb` bigint DEFAULT NULL,
  `max_heap_mb` bigint DEFAULT NULL,
  `internal_storage_used_gb` bigint DEFAULT NULL,
  `external_storage_used_gb` bigint DEFAULT NULL,
  `timezone_display_name` varchar(255) DEFAULT NULL,
  `boot_time` bigint DEFAULT NULL,
  `battery_temperature_c` float DEFAULT NULL,
  `battery_voltage_mv` int DEFAULT NULL,
  `battery_source` varchar(50) DEFAULT NULL,
  `has_accelerometer` tinyint(1) DEFAULT NULL,
  `has_gyroscope` tinyint(1) DEFAULT NULL,
  `has_magnetometer` tinyint(1) DEFAULT NULL,
  `has_proximity` tinyint(1) DEFAULT NULL,
  `has_light` tinyint(1) DEFAULT NULL,
  `kernel_version` text,
  `is_debuggable` tinyint(1) DEFAULT NULL,
  `is_test_build` tinyint(1) DEFAULT NULL,
  `app_signature_count` int DEFAULT NULL,
  `app_target_sdk` int DEFAULT NULL,
  `app_installer` varchar(255) DEFAULT NULL,
  `system_feature_count` int DEFAULT NULL,
  `system_features` longtext,
  `bootloader` varchar(255) DEFAULT NULL,
  `radio_version` varchar(100) DEFAULT NULL,
  `build_serial` varchar(255) DEFAULT NULL,
  `java_vm_version` varchar(100) DEFAULT NULL,
  `java_vm_name` varchar(100) DEFAULT NULL,
  `os_name` varchar(50) DEFAULT NULL,
  `user_language` varchar(50) DEFAULT NULL,
  `user_region` varchar(50) DEFAULT NULL,
  `uptime_seconds` bigint DEFAULT NULL,
  `uptime_boot` bigint DEFAULT NULL,
  `system_load` float DEFAULT NULL,
  `ui_mode` int DEFAULT NULL,
  `font_scale` float DEFAULT NULL,
  `screen_layout` int DEFAULT NULL,
  `smallest_width_dp` int DEFAULT NULL,
  `keyboard` int DEFAULT NULL,
  `touchscreen` int DEFAULT NULL,
  `navigation` int DEFAULT NULL,
  PRIMARY KEY (`counter`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb3');
    }

    public function down()
    {
        $this->db->query('DROP TABLE IF EXISTS `tbl_device_profile`');
    }
}
