-- Create tbl_location table
CREATE TABLE IF NOT EXISTS `tbl_location` (
    `counter` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `owner_id` int(11) UNSIGNED NOT NULL,
    `device_id` varchar(100) DEFAULT NULL,
    `latitude` decimal(10,8) DEFAULT NULL COMMENT 'GPS latitude coordinate',
    `longitude` decimal(11,8) DEFAULT NULL COMMENT 'GPS longitude coordinate',
    `accuracy` float DEFAULT NULL COMMENT 'Location accuracy in meters',
    `altitude` float DEFAULT NULL COMMENT 'Altitude in meters above sea level',
    `bearing` float DEFAULT NULL COMMENT 'Bearing in degrees',
    `speed` float DEFAULT NULL COMMENT 'Speed in meters/second',
    `provider` varchar(50) DEFAULT NULL COMMENT 'Location provider (gps, network, etc.)',
    `location_time` bigint(20) UNSIGNED DEFAULT NULL COMMENT 'Timestamp when location was recorded (Unix milliseconds)',
    `status` varchar(50) DEFAULT 'no_location_found' COMMENT 'success, no_location_found, error',
    `extracted_at` bigint(20) UNSIGNED DEFAULT NULL,
    `created_at` datetime DEFAULT NULL,
    `updated_at` datetime DEFAULT NULL,
    PRIMARY KEY (`counter`),
    KEY `owner_id` (`owner_id`),
    KEY `device_id` (`device_id`),
    KEY `extracted_at` (`extracted_at`),
    KEY `location_time` (`location_time`),
    KEY `owner_extracted` (`owner_id`,`extracted_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stores device location data extracted from Android';

-- Create tbl_activity table
CREATE TABLE IF NOT EXISTS `tbl_activity` (
    `counter` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `owner_id` int(11) UNSIGNED NOT NULL,
    `device_id` varchar(100) DEFAULT NULL,
    `status` varchar(100) DEFAULT 'feature_not_fully_implemented' COMMENT 'Status of activity recognition',
    `activity_type` varchar(100) DEFAULT NULL COMMENT 'Detected activity type (walking, running, driving, etc.)',
    `confidence` int(3) UNSIGNED DEFAULT 0 COMMENT 'Confidence level (0-100)',
    `info` text DEFAULT NULL COMMENT 'Additional information about activity',
    `is_interactive` tinyint(1) DEFAULT 0 COMMENT '1 = device interactive, 0 = not interactive',
    `battery_level` int(3) UNSIGNED DEFAULT NULL COMMENT 'Battery percentage (0-100)',
    `charging_status` varchar(50) DEFAULT NULL COMMENT 'charging, discharging, full, unknown',
    `network_type` varchar(50) DEFAULT NULL COMMENT 'wifi, mobile, ethernet, unknown',
    `screen_on` tinyint(1) DEFAULT 0 COMMENT '1 = screen on, 0 = screen off',
    `extracted_at` bigint(20) UNSIGNED DEFAULT NULL,
    `activity_time` bigint(20) UNSIGNED DEFAULT NULL COMMENT 'Timestamp when activity was detected (Unix milliseconds)',
    `created_at` datetime DEFAULT NULL,
    `updated_at` datetime DEFAULT NULL,
    PRIMARY KEY (`counter`),
    KEY `owner_id` (`owner_id`),
    KEY `device_id` (`device_id`),
    KEY `extracted_at` (`extracted_at`),
    KEY `activity_type` (`activity_type`),
    KEY `activity_time` (`activity_time`),
    KEY `owner_extracted` (`owner_id`,`extracted_at`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stores device activity and sensor data extracted from Android';