<div class="content-wrapper">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1><i class="fas fa-file-alt mr-1"></i> PHP Error Logs</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="<?= base_url('admin/dashboard') ?>">Admin</a></li>
                        <li class="breadcrumb-item"><a href="<?= base_url('admin/logs') ?>">Logs</a></li>
                        <li class="breadcrumb-item active">PHP Errors</li>
                    </ol>
                </div>
            </div>
        </div>
    </section>

    <section class="content">
        <div class="container-fluid">
            <?php if (session()->getFlashdata('message')): ?>
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?= session()->getFlashdata('message') ?>
            </div>
            <?php endif; ?>
            <?php if (session()->getFlashdata('error')): ?>
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <?= session()->getFlashdata('error') ?>
            </div>
            <?php endif; ?>

            <div class="callout callout-info shadow-sm mb-4">
                <h5><i class="fas fa-info-circle mr-2"></i>PHP Error Logs</h5>
                <p class="mb-0">PHP runtime error logs generated by CodeIgniter. View, inspect, and clean up log files from the <code>writable/logs</code> directory.</p>
            </div>

            <div class="card card-outline card-secondary shadow-sm">
                <div class="card-header">
                    <div class="btn-group">
                        <a href="<?= base_url('admin/logs') ?>" class="btn btn-sm btn-outline-primary"><i class="fas fa-list mr-1"></i>All</a>
                        <a href="<?= base_url('admin/logs/access') ?>" class="btn btn-sm btn-outline-primary"><i class="fas fa-sign-in-alt mr-1"></i>Access</a>
                        <a href="<?= base_url('admin/logs/errors') ?>" class="btn btn-sm btn-outline-danger"><i class="fas fa-exclamation-triangle mr-1"></i>Errors</a>
                        <a href="<?= base_url('admin/logs/php-errors') ?>" class="btn btn-sm btn-secondary"><i class="fas fa-file-alt mr-1"></i>PHP Errors</a>
                        <a href="<?= base_url('admin/logs/api') ?>" class="btn btn-sm btn-outline-info"><i class="fas fa-code mr-1"></i>API</a>
                        <a href="<?= base_url('admin/logs/fcm') ?>" class="btn btn-sm btn-outline-info"><i class="fas fa-fire mr-1"></i>FCM</a>
                        <a href="<?= base_url('admin/logs/maintenance') ?>" class="btn btn-sm btn-outline-warning"><i class="fas fa-shield-alt mr-1"></i>Maintenance</a>
                        <a href="<?= base_url('admin/logs/engine') ?>" class="btn btn-sm btn-outline-secondary"><i class="fas fa-robot mr-1"></i>Engine</a>
                    </div>
                    <div class="card-tools">
                        <span class="badge badge-secondary"><?= $total ?> log files</span>
                        <form method="post" action="<?= base_url('admin/logs/clear-error-files') ?>" style="display:inline" class="ml-2">
                            <?= csrf_field() ?>
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Delete all PHP log files?')"><i class="fas fa-trash"></i> Delete All</button>
                        </form>
                    </div>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <table class="table table-hover" id="phpErrorTable">
                            <thead class="thead-light">
                                <tr>
                                    <th>#</th>
                                    <th>Filename</th>
                                    <th>Size</th>
                                    <th>Lines</th>
                                    <th>Last Modified</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (empty($error_files)): ?>
                                <tr><td colspan="6" class="text-center text-muted py-4">No PHP log files found.</td></tr>
                                <?php else: ?>
                                <?php $i = 1; ?>
                                <?php foreach ($error_files as $f): ?>
                                <tr>
                                    <td class="text-muted"><?= $i++ ?></td>
                                    <td><code><?= htmlspecialchars($f['filename']) ?></code></td>
                                    <td><?= number_format($f['size'] / 1024, 1) ?> KB</td>
                                    <td><span class="badge badge-secondary"><?= number_format($f['lines']) ?></span></td>
                                    <td><small><?= htmlspecialchars($f['modified'] ?? '-') ?></small></td>
                                    <td>
                                        <a href="<?= base_url('admin/logs/view-error-file/' . $f['filename']) ?>" class="btn btn-sm btn-info" title="View"><i class="fas fa-eye"></i></a>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script>
$(document).ready(function() {
    $('#phpErrorTable').DataTable({
        order: [[4, 'desc']],
        searching: false,
        paging: false,
        responsive: true,
    });
});
</script>
