<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forensic Report - <?= esc($device['device_model'] ?? 'Unknown Device') ?></title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.6; margin: 0; padding: 20px; background-color: #f4f6f9; }
        .header { background-color: #343a40; color: #ffffff; padding: 20px; border-radius: 5px 5px 0 0; text-align: center; }
        .header h1 { margin: 0; font-size: 24px; font-weight: 300; }
        .content { background-color: #ffffff; padding: 30px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 5px 5px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        h2 { color: #343a40; border-bottom: 2px solid #007bff; padding-bottom: 5px; margin-top: 30px; }
        .card { border: 1px solid #ddd; border-radius: 4px; padding: 15px; margin-bottom: 20px; background-color: #fdfdfd; }
        .card-header { font-weight: bold; margin-bottom: 10px; color: #495057; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        .narrative { white-space: pre-wrap; background-color: #f8f9fa; padding: 15px; border-left: 4px solid #17a2b8; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table, th, td { border: 1px solid #dee2e6; }
        th, td { padding: 10px; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .text-danger { color: #dc3545; }
        .text-warning { color: #ffc107; }
        .footer { text-align: center; margin-top: 40px; font-size: 12px; color: #6c757d; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Forensic Analysis Report</h1>
        <p>Device: <?= esc($device['device_model'] ?? 'Unknown Device') ?> (ID: <?= esc($device['device_id']) ?>)</p>
        <p>Generated: <?= esc($generated) ?></p>
    </div>
    
    <div class="content">
        <h2>Executive Summary</h2>
        <div class="narrative"><?= esc($narrative) ?></div>
        
        <h2>Communication Analysis</h2>
        <?php if (!empty($data['calls'])): ?>
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Count</th>
                        <th>Total Duration (s)</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['calls'] as $c): ?>
                        <tr>
                            <td><?= esc($c['type'] ?? 'Unknown') ?></td>
                            <td><?= esc($c['count']) ?></td>
                            <td><?= esc($c['total_duration']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p>No call records found.</p>
        <?php endif; ?>
        
        <h2>Risk Assessment & Anomalies</h2>
        <?php if (!empty($data['anomalies'])): ?>
            <?php foreach($data['anomalies'] as $a): ?>
                <div class="card">
                    <div class="card-header">
                        <?= esc($a['algorithm_name'] ?? $a['algorithm_id']) ?> - 
                        <span class="<?= $a['severity'] === 'High' ? 'text-danger' : 'text-warning' ?>">
                            <?= esc($a['severity']) ?> (Score: <?= esc($a['score']) ?>)
                        </span>
                    </div>
                    <div>
                        <strong>Anomaly:</strong> <?= esc($a['anomaly']) ?><br>
                        <strong>Timestamp:</strong> <?= esc($a['event_timestamp']) ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <p>No high-risk anomalies detected.</p>
        <?php endif; ?>
        
        <h2>Application Delta Snapshot</h2>
        <?php if (!empty($data['apps'])): ?>
            <table>
                <thead>
                    <tr>
                        <th>App Name</th>
                        <th>Package</th>
                        <th>Type</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data['apps'] as $app): ?>
                        <tr>
                            <td><?= esc($app['app_name']) ?></td>
                            <td><?= esc($app['package_name']) ?></td>
                            <td><?= $app['is_system'] ? 'System' : 'User' ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <p>No app delta recorded.</p>
        <?php endif; ?>
    </div>
    
    <div class="footer">
        <p>This report is automatically generated by Eaves Droid Forensic ML Engine.</p>
        <p>CONFIDENTIAL & PROPRIETARY</p>
    </div>
</body>
</html>
